require('iamthatog.set')
require('iamthatog.keymaps')
require('iamthatog.plugins-config.colorscheme')
require('iamthatog.plugins-config.comment')
require('iamthatog.plugins-config.nvim-tree')
require('iamthatog.plugins-config.lualine')
require('iamthatog.plugins-config.telescope')
require('iamthatog.plugins-config.harpoon')
require('iamthatog.plugins-config.nvim-cmp')
require('iamthatog.plugins-config.lsp.lsp')
require('iamthatog.plugins-config.lsp.mason')
require('iamthatog.plugins-config.lsp.lspsaga')
require('iamthatog.plugins-config.nvm-autopairs')
require('iamthatog.plugins-config.nvim-treesitter')
require('iamthatog.plugins-config.gitsigns')
require('iamthatog.plugins-config.bufferline')

