require("config.options")
require("config.lazy")
require("plugins.telescope")
require("config.keymaps")
require("plugins.color-scheme")
require("plugins.comment")
require("plugins.lualine")
require("plugins.harpoon")
require("plugins.nvim-neoclip")
require("plugins.lsp.lsp")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.nvm-autopairs")
require("plugins.nvim-treesitter")
require("plugins.nvim-ts-autotag")
require("plugins.gitsigns")
require("plugins.bufferline")
require("plugins.luasnip")

print("=========== Hello OG! ===========")
print("• Check out your todos ✅ ")
print("• Iterate fast ⚙️ ")
print("• Do the hard things 💪 ")
print("• Have fun 😎 ")
print("• Learn everyday 📚 ")
print("• Be a leader 👑")
print("You are smart 🧠 ")
print("=================================")
print("#moonshotMindset! 🚀")
